### ISSUE TITLE
Program fail in raspi image

### ISSUE THREAD

**Issue by nathanmutin** [opensight-cv/opensight#2]
I create an issue here because it seems that I can't on [opsi-gen](https://github.com/opensight-cv/opsi-gen).

First, thank you for what you are doing this is awesome !!
So, I tried to test the raspberry image but the camera didn't seem to work and the dashboard wasn't here. I decided to ssh into the raspberry and looked at the opensight service which had effectivly failed.
When I tried to manualy re-run the program, I had this issue : 
```
Traceback (most recent call last):
  File "/bin/opensight", line 81, in <module>
    main()
  File "/bin/opensight", line 70, in main
    program = make_program(package_path)
  File "/bin/opensight", line 31, in make_program
    program.manager.register_module(ModulePath(dir, path))
  File "/usr/lib/python3/dist-packages/opsi/manager/manager.py", line 73, in register_module
    module = import_module(path)
  File "/usr/lib/python3/dist-packages/opsi/manager/manager.py", line 39, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/opsi/modules/input.py", line 87, in <module>
    class CameraInput(Function):
  File "/usr/lib/python3/dist-packages/opsi/modules/input.py", line 97, in CameraInput
    @dataclass
  File "/usr/lib/python3/dist-packages/opsi/modules/input.py", line 99, in Settings
    mode: get_modes()
  File "/usr/lib/python3/dist-packages/opsi/modules/input.py", line 70, in get_modes
    "Cam {0}: {1} @ {2:g} fps".format(cam, resolution, float(max(fpses)))
ValueError: max() arg is an empty sequence
```

**Comment by 132ikl** [comment]
Yes, this is the correct repository for issues. There's a fix for this which will be pushed soon. Also, CameraServer does not currently actually go to the dashboard however we will likely be rewriting the CameraServer module in the near future. I wouldn't recommend extensively testing OpenSight until the first beta release which should be coming out very soon hopefully. Until then, opsi isn't quite in a stable enough state to be useful. If you join our [Discord](https://discord.gg/hPqpdsK) you can get notified when said release comes out and join in discussion.

**Comment by nathanmutin** [comment]
Ok nice. When I said the dashboard I meant the webdashboard, I don't know if you're talking about it or about the smartdashboard/shuffleboard.
And for the Discord I'm already on it but just inactive 😀

**Comment by 132ikl** [comment]
Hi, this should certainly be fixed now. It should also work properly with SmartDashboard/Shuffleboard if you want to use that. If you want to wait for the actual beta, that will be coming out within the next couple of days.

**Comment by nathanmutin** [comment]
Cool thanks.
